# Generated by Django 4.0.5 on 2022-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
