# Generated by Django 4.0.5 on 2022-07-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='user',
        ),
    ]
