# Generated by Django 4.0.5 on 2022-07-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_remove_meetup_date_remove_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=1999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='luckykamshak@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
