# Generated by Django 4.0.5 on 2022-07-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0011_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
